spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/booksdb
    username: postgres
    password: GONZALITR0
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: 8080


